// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgwKo3dJe_sCvUFXkG3mj9LE3gPjq7jPs',
    appId: '1:200618671307:web:e5dc5c3d22a37353b96f4e',
    messagingSenderId: '200618671307',
    projectId: 'ecommerce-55dd8',
    authDomain: 'ecommerce-55dd8.firebaseapp.com',
    storageBucket: 'ecommerce-55dd8.firebasestorage.app',
    measurementId: 'G-FGY8CE9KXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdtP2OLhrL20FMpL9K7LxuxevvMiu90M',
    appId: '1:200618671307:android:9ed3ee11a4b741f6b96f4e',
    messagingSenderId: '200618671307',
    projectId: 'ecommerce-55dd8',
    storageBucket: 'ecommerce-55dd8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgwKo3dJe_sCvUFXkG3mj9LE3gPjq7jPs',
    appId: '1:200618671307:web:13ae624670770b22b96f4e',
    messagingSenderId: '200618671307',
    projectId: 'ecommerce-55dd8',
    authDomain: 'ecommerce-55dd8.firebaseapp.com',
    storageBucket: 'ecommerce-55dd8.firebasestorage.app',
    measurementId: 'G-K1L5PEE6X0',
  );
}
