name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Générer firebase_options.dart
        run: |
          echo "import 'package:firebase_core/firebase_core.dart';" > lib/firebase_options.dart
          echo "" >> lib/firebase_options.dart
          echo "class DefaultFirebaseOptions {" >> lib/firebase_options.dart
          echo "  static FirebaseOptions get currentPlatform => const FirebaseOptions(" >> lib/firebase_options.dart
          echo "    apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> lib/firebase_options.dart
          echo "    appId: '${{ secrets.FIREBASE_APP_ID }}'," >> lib/firebase_options.dart
          echo "    messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> lib/firebase_options.dart
          echo "    projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> lib/firebase_options.dart
          echo "    authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> lib/firebase_options.dart
          echo "    storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> lib/firebase_options.dart
          echo "  );" >> lib/firebase_options.dart
          echo "}" >> lib/firebase_options.dart

      - name: Format check
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze --no-fatal-warnings

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Check coverage (≥ 50%)
        run: |
          sudo apt-get install -y lcov
          COVERAGE=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}' | sed 's/%//')
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
            echo "Coverage is less than 50%"
            exit 1
          fi

      - name: Build Web
        run: flutter build web

      - name: Upload Web artefact
        uses: actions/upload-artifact@v4
        with:
          name: build-web
          path: build/web
